# This is a basic workflow to help you get started with Actions

name: Pytest on push and on pull requests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: install femmt package
        run: |
            sudo apt-get update
            sudo apt install libsm6 libxext6 ffmpeg libfontconfig1 libxrender1 libgl1-mesa-glx
            # pip install opencv-python
            pip install -e .
            pip install pytest
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Start testing...
          cd tests/
          pytest femmt_test.py
          echo tests finished.
          
