# This is a basic workflow to help you get started with Actions

name: Pytest on push and on pull requests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: install femmt package
        run: |
            sudo apt-get update
            # Problem with OSError: libGLU.so.1: connot open shared object file
            # Answer here: https://stackoverflow.com/questions/55313610/importerror-libgl-so-1-cannot-open-shared-object-file-no-such-file-or-directo
            sudo apt install libsm6 libxext6 ffmpeg libfontconfig1 libxrender1 libglu1
            pip install opencv-python
            pip install -e .
            pip install pytest
      # Runs a set of commands using the runners shell
      - name: Run pytests
        run: |
          echo Start testing...
          cd tests/
          pytest femmt_test.py
          echo tests finished.
          
      - name: Install sphinx and build documentation with sphinx
        run: |
          pip install sphinx sphinx-multiversion sphinx_rtd_theme sphinxcontrib-email standford-theme
          pwd
          ls
          cd sphinx/
          make html
          
